### ISSUE TITLE
Connection-pool nil problem when using master

### ISSUE THREAD

**Issue by K1D77A** [fukamachi/dexador#111]
![image](https://user-images.githubusercontent.com/10334164/151014646-5c033684-4f10-4e58-ba52-205dd2a67c23.png)
I have cloned master but some of the code I was relying on was still using the old hack to avoid connection pooling, however it seems that this old code with the master version broke, as soon as I removed the :use-connection-pool nil I have not had anymore issues. 
Sorry that the error is so vague it was caught in a running program which catches all conditions and resignals them.

**Comment by ajberkley** [comment]
That's not good!  I was careful to try and preserve the ability to do external connection pooling, but it's possible I made a mistake or wrong assumption.  Do you know the assumptions you are making about passing in streams / returning streams?  Of course better would be a real stack trace!

**Comment by K1D77A** [comment]
Hi, I was not performing any manual connection pooling, I was use using :use-connection-pool nil as an argument in order to prevent the weird bugs that were present before you fixed it. Unfortunately I do not have access to a full stack trace :(

**Comment by ajberkley** [comment]
Ah, OK.  The message usually indicates a proxy issue or an issue with self signed certificates in the chain somewhere.  Unfortunately I think I'd need some more info to debug :(

**Comment by ajberkley** [comment]
Maybe the reason it is more stable with use-connection-pool t is because you are hitting the DNS and opening new connections less often.  One question is whether dexador should arbitrarily retry things for all possible network errors.  What do you think?  I don't know why it would be less stable then before unless I deleted a big retry on all possible errors in dexador, but I don't see that I did that (though the control flow of the code is... unnecessarily complex... and hard to reason about).

With regards to getting ESYSTEM plus ERRNO = 0 in the dns call, this is a big can of worms.  I don't think ERRNO is well defined in the lisp context, because you can get interrupted by gcs which make system calls, etc, and I don't think implementations restore errno... but I'd have to look and see.  I'd prefer is someone with more common lisp network experience would just tell me the answer though.

It may be that this should be handled by usocket.

**Comment by ajberkley** [comment]
Closing as I am 99% sure this isn't a dexador problem.  Please re-open if you can pin it down more.
