### ISSUE TITLE
Support global proxy settings

### ISSUE THREAD

**Issue by cireu** [fukamachi/dexador#93]
Currently dexador only supports `proxy` param in `request` function. It's quite inconvenient for user who use CL application depends on dexador to do HTTP request.

Maybe dexador can add a dynamic parameter (e.g `*proxy*`) to inject proxy settings into existing function calls dexador:request. Or we can make dexador honor the environment variable `http_proxy` `https_proxy`.

**Comment by ajberkley** [comment]
This is an old issue, but I felt I shouldn't just close it since you took the time to write it!

I think you are talking about a case where you use a library that uses dexador and that library doesn't provide a way to specify a global proxy?  I would think in this case it is the wrapper library job to provide the feature.  You could also just wrap or even redefine dexador::request to do what you want since you seem willing to accept the incomplete encapsulation provided by whatever library being used.

I don't really object to doing this for :proxy but would like to understand more about your problem...

**Comment by cireu** [comment]
> I think you are talking about a case where you use a library that uses dexador and that library doesn't provide a way to specify a global proxy? I would think in this case it is the wrapper library job to provide the feature. 

If there's a CL program use dexador and it doesn't allow us to run Lisp code during its execution, we can't do anything with it.

> I don't really object to doing this for :proxy but would like to understand more about your problem...

IMO the env var `http_proxy` and `https_proxy` is widely used in *nix system and Windows, it's not bad to support it.

**Comment by ajberkley** [comment]
See #125 .  You can try this out by pulling and using https://github.com/ajberkley/dexador/tree/master

**Comment by ajberkley** [comment]
Ugh, won't work on windows

**Comment by ajberkley** [comment]
Merged request.
